files:
  - source: /tango_n5/source/*.csv
    translation: /tango_n5/translation/%two_letters_code%/%file_name% (Crowdin).%file_extension%
    scheme: 'source_phrase,none,context,translation,none,none,none'
  - source: /tango_n4/source/*.csv
    translation: /tango_n4/translation/%two_letters_code%/%file_name% (Crowdin).%file_extension%
    scheme: 'source_phrase,none,context,translation,none,none,none'
