project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
project_identifier: brigadasos
preserve_hierarchy: true

files:
  - source: /**/translation/source.csv
    translation: /**/translation/%two_letters_code%.%file_extension%
    scheme: 'source_phrase,none,context,translation,none,labels'
