project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
project_identifier: vuetify
preserve_hierarchy: true

files:
  - source: /tango_n5/source/*.csv
    translation: /tango_n5/translation/%two_letters_code%/%file_name%.%file_extension%
  - source: /tango_n4/source/*.csv
    translation: /tango_n4/translation/%two_letters_code%/%file_name%.%file_extension%
